### PR TITLE
Update install_via_centos7.md

### PR DESCRIPTION
**Pull request by extremerotary**
Update current stable to 4.3 and additional information on new rabbitMQ version installing and additional HAProxy info.

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Hi @extremerotary I'm wondering if all this content is applicable here or should be in the [cluster guide](https://github.com/2600hz/docs-sysadmin/blob/master/doc/kazoo/cluster-guide.md) instead? The intent of this doc is to get an all-in-one server setup. I like adding notes about "If you want RabbitMQ on a separate server, consult the cluster guide" or whatever for multi-server instructions.

Thoughts?

**Comment by extremerotary** [comment]
Sure, sounds good. I'll make the necessary updates and recommit

**Comment by extremerotary** [comment]
@jamesaimonetti 
One thing I wanted to check - In the core/config.ini, the default cookie is no longer change_me. This causes conflicts with freeswitch, kazoo apps, and bigcouch. 
Do you want me to add steps on how to change the cookie for each of those components or should I commit changing the core/config.ini back to change_me?

**Comment by jamesaimonetti** [comment]
@extremerotary where do you see that? I see https://github.com/2600hz/kazoo-configs-core/blob/master/core/config.ini as having `change_me` still as the default cookie.

But yes, calling attention to changing them and making special mention that ecallmgr and FreeSWITCH/mod_kazoo must match would be great!

**Comment by jamesaimonetti** [comment]
Merged

**Pull request closed without merging**
